"""increased the image length

Revision ID: 7c5aa3f32aab
Revises: 5e5ae415c735
Create Date: 2025-02-02 14:32:44.523676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c5aa3f32aab'
down_revision = '5e5ae415c735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=355),
               existing_nullable=False,
               existing_server_default=sa.text("'default.jpg'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=355),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False,
               existing_server_default=sa.text("'default.jpg'::character varying"))

    # ### end Alembic commands ###
